---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-cert
  namespace: default
spec:
  secretName: local-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.tenciolabs.com"
  dnsNames:
  - "local.tenciolabs.com"
  - "*.local.tenciolabs.com"
