---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
    - 172.16.10.3-172.16.10.4
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
